apiVersion: v1
kind: Secret
metadata:
  name: drone-credentials
  namespace: drone
type: Opaque
stringData:
  drone-rpc-secret: "drone-rpc-secret-key"
  drone-gitea-client-id: "86a1cc10-aec6-4069-b11a-e799ed5961e9"
  drone-gitea-client-secret: "gto_lxnfsduraaxe3lykbhevftntiw6imvsh3l5wbqw6l3gy5xxpb4qq"
  drone-admin-user: "gitea_admin"