apiVersion: v1
kind: Secret
metadata:
  name: drone-credentials
  namespace: drone
type: Opaque
stringData:
  drone-rpc-secret: "drone-rpc-secret-key"
  drone-gitea-client-id: "89a01d12-87dc-4d3e-8021-6f94f6b412a0"
  drone-gitea-client-secret: "gto_q4u7kotkggjz7cijnawdsosnxv5on4t5ae2qhuhx66kkgu7jmdrq"
  drone-admin-user: "gitea_admin"