apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
  namespace: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
        - name: drone-server
          image: drone/drone:2
          ports:
            - containerPort: 80
          env:
            - name: DRONE_GITEA_SERVER
              value: "http://172.17.0.1:3000"
            - name: DRONE_GITEA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: drone-credentials
                  key: drone-gitea-client-id
            - name: DRONE_GITEA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-credentials
                  key: drone-gitea-client-secret
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-credentials
                  key: drone-rpc-secret
            - name: DRONE_SERVER_HOST
              value: "172.17.0.1:3001"
            - name: DRONE_SERVER_PROTO
              value: "http"
            - name: DRONE_DATABASE_DRIVER
              value: "sqlite3"
            - name: DRONE_DATABASE_DATASOURCE
              value: "/data/database.sqlite"
            - name: DRONE_USER_CREATE
              value: "username:gitea_admin,admin:true"
            - name: DRONE_USER_FILTER
              value: "gitea_admin"
            - name: DRONE_GIT_ALWAYS_AUTH
              value: "false"
            - name: DRONE_GITEA_SKIP_VERIFY
              value: "true"
          volumeMounts:
            - name: drone-data
              mountPath: /data
      volumes:
        - name: drone-data
          persistentVolumeClaim:
            claimName: drone-data-pvc