apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner
  namespace: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-runner
  template:
    metadata:
      labels:
        app: drone-runner
    spec:
      containers:
        - name: drone-runner
          image: drone/drone-runner-docker:1
          env:
            - name: DRONE_RPC_HOST
              value: "drone.drone.svc.cluster.local:80"
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-credentials
                  key: drone-rpc-secret
            - name: DRONE_RUNNER_CAPACITY
              value: "2"
            - name: DRONE_RUNNER_NAME
              value: "drone-runner"
            - name: DRONE_ENVIRONMENT
              value: "MLFLOW_ENDPOINT MLFLOW_TRACKING_URI KUBEFLOW_ENDPOINT LAKEFS_ENDPOINT MINIO_ENDPOINT LAKEFS_ACCESS_KEY LAKEFS_SECRET_KEY MINIO_ACCESS_KEY MINIO_SECRET_KEY"
            # MLOps Service Endpoints from ConfigMap
            - name: MLFLOW_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: MLFLOW_ENDPOINT
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: MLFLOW_TRACKING_URI
            - name: KUBEFLOW_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: KUBEFLOW_ENDPOINT
            - name: LAKEFS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: LAKEFS_ENDPOINT
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: MINIO_ENDPOINT
            # MLOps Credentials from Secret
            - name: LAKEFS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: drone-additional-credentials
                  key: LAKEFS_ACCESS_KEY
            - name: LAKEFS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: drone-additional-credentials
                  key: LAKEFS_SECRET_KEY
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: drone-additional-credentials
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: drone-additional-credentials
                  key: MINIO_SECRET_KEY
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock