apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner
  namespace: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-runner
  template:
    metadata:
      labels:
        app: drone-runner
    spec:
      containers:
        - name: drone-runner
          image: drone/drone-runner-docker:1
          env:
            - name: DRONE_RPC_HOST
              value: "drone.drone.svc.cluster.local:80"
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-credentials
                  key: drone-rpc-secret
            - name: DRONE_RUNNER_CAPACITY
              value: "2"
            - name: DRONE_RUNNER_NAME
              value: "drone-runner"
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock