apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.16.1
        command: ["mlflow"]
        args:
          - "server"
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "5000"
          - "--backend-store-uri"
          - "sqlite:///mlflow/mlflow.db"
          - "--default-artifact-root"
          - "s3://$(MINIO_BUCKET)/"
          - "--serve-artifacts"
        env:
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: MINIO_ENDPOINT
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: MINIO_SECRET_KEY
        - name: MINIO_BUCKET
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: MINIO_BUCKET
        - name: MLFLOW_S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: MLFLOW_S3_ENDPOINT_URL
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: AWS_DEFAULT_REGION
        - name: MLFLOW_S3_IGNORE_TLS
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: MLFLOW_S3_IGNORE_TLS
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: mlflow-data
          mountPath: /mlflow
        resources:
          requests:
            memory: "2000Mi"
            cpu: "1000m"
          limits:
            memory: "4000Mi"
            cpu: "2000m"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: mlflow-data
        persistentVolumeClaim:
          claimName: mlflow-data-pvc