"""
Pytest configuration for langgraph-temporal-agent tests.
"""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

import pytest

# Load Langfuse credentials from .langfuse.env (generated by install_langfuse.sh)
_TEST_ROOT = Path(__file__).parent.parent
load_dotenv(_TEST_ROOT / ".langfuse.env")


@pytest.fixture(autouse=True)
def _setup_test_env(monkeypatch):
    """Set test-appropriate environment variables.

    By default, Langfuse tracing is **disabled** for tests so that they run
    quickly and deterministically without any external dependencies.  To enable
    Langfuse tracing for a test run, set the ``LANGFUSE_TEST_TRACING`` env var
    before running pytest::

        export LANGFUSE_TEST_TRACING=1
        pytest tests/ -v

    When enabled, credentials are loaded from ``.langfuse.env`` (generated by
    ``install_langfuse.sh``), connecting tests to the local Langfuse UI at
    http://localhost:3000/project/local-project.
    """
    monkeypatch.setenv("APP_ENV", "local")

    # Expose Langfuse credentials from .langfuse.env so that both the
    # observability modules (which read os.environ at import time) and the
    # integration tests (which call _get_creds_from_env_or_file()) agree on
    # what credentials are configured.
    _lf_secret = os.getenv("LANGFUSE_SECRET_KEY", "")
    _lf_public = os.getenv("LANGFUSE_PUBLIC_KEY", "")
    _lf_host = os.getenv("LANGFUSE_HOST", os.getenv("LANGFUSE_BASE_URL", ""))
    if _lf_secret:
        monkeypatch.setenv("LANGFUSE_SECRET_KEY", _lf_secret)
    if _lf_public:
        monkeypatch.setenv("LANGFUSE_PUBLIC_KEY", _lf_public)
    if _lf_host:
        monkeypatch.setenv("LANGFUSE_HOST", _lf_host)

    # Only set LANGFUSE_TEST_TRACING if not already set externally.
    # This allows users to opt in via: LANGFUSE_TEST_TRACING=1 pytest ...
    if "LANGFUSE_TEST_TRACING" not in os.environ:
        monkeypatch.setenv("LANGFUSE_TEST_TRACING", "0")


@pytest.fixture(autouse=True)
def _reset_langfuse_between_tests(monkeypatch, request):
    """Reset the Langfuse client singleton between tests.

    This prevents state leakage between tests when Langfuse tracing is
    enabled.  The reset happens as an autouse fixture so every test gets
    a fresh client.
    """
    yield  # Run the test

    # After each test, reset the Langfuse singleton
    from app.infrastructure.observability.client import reset_langfuse

    reset_langfuse()
