apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
  namespace: zot
data:
  config.json: |
    {
      "distSpecVersion": "1.1.0-dev",
      "http": {
        "address": "0.0.0.0",
        "port": "5000"
      },
      "storage": {
        "rootDirectory": "/var/lib/registry",
        "dedupe": false,
        "storageDriver": {
          "name": "s3",
          "bucket": "zot-registry",
          "regionendpoint": "http://minio.minio.svc.cluster.local:9000",
          "accesskey": "minioadmin",
          "secretkey": "minioadmin123",
          "region": "us-east-1",
          "secure": false,
          "skipverify": true
        }
      },
      "log": {
        "level": "debug",
        "output": "/dev/stdout"
      },
      "extensions": {
        "ui": {
          "enable": true
        },
        "search": {
          "enable": true
        }
      }
    }