apiVersion: v1
kind: Secret
metadata:
  name: forgejo-credentials
  namespace: forgejo
type: Opaque
stringData:
  secret-key: "6182da9dff1946f817107aec0bc0e80ea9570b18daecfafd03557dbb78793552"
  internal-token: "6182da9dff1946f817107aec0bc0e80ea9570b18daecfafd03557dbb78793552"
  admin-token: "6182da9dff1946f817107aec0bc0e80ea9570b18daecfafd03557dbb78793552"
  admin-username: "forgejo_admin"
  admin-password: "forgejo_password"
  admin-email: "admin@forgejo.local"