apiVersion: v1
kind: Secret
metadata:
  name: gitea-credentials
  namespace: gitea
type: Opaque
stringData:
  admin-username: "gitea_admin"
  admin-password: "gitea_admin_password"
  admin-email: "gitea@example.com"
  secret-key: "changeme-changeme-changeme-changeme"
  internal-token: "changeme-changeme-changeme-changeme"